language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mkdir -p build/coverage
  - composer self-update
  - composer update --prefer-source -v --dev

script: 
  - phpunit --bootstrap=tests/bootstrap.php

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
