language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mkdir -p build/coverage
  - composer self-update
  - composer update --prefer-source -v --dev

script: 
  - ./vendor/bin/phpunit --bootstrap=./tests/bootstrap.php
  - ./vendor/bin/phpcs -n --standard=PSR2 ./src ./tests

after_script:
  - php vendor/bin/phpcov.php --merge --clover build/logs/clover.xml --whitelist library build/coverage
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
