<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'tteMaintenance\Module'                        => __DIR__ . '/Module.php',
    'tteMaintenance\Controller\SkeletonController' => __DIR__ . '/src/tteMaintenance/Controller/SkeletonController.php',
    'tteMaintenanceTest\Framework\TestCase'        => __DIR__ . '/tests/tteMaintenance/Framework/TestCase.php',
    'tteMaintenanceTest\SampleTest'                => __DIR__ . '/tests/tteMaintenance/SampleTest.php',
);