<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Maintenance\Module'                        => __DIR__ . '/Module.php',
    'Maintenance\Controller\SkeletonController' => __DIR__ . '/src/Maintenance/Controller/SkeletonController.php',
    'MaintenanceTest\Framework\TestCase'        => __DIR__ . '/tests/Maintenance/Framework/TestCase.php',
    'MaintenanceTest\SampleTest'                => __DIR__ . '/tests/Maintenance/SampleTest.php',
);